"# Set owner and permission for configuration directory.
#
# `reframe-streamer` runs as `root` and `reframe-server` runs as `reframe`.
# Type Path Mode User Group Age Argument
z /etc/reframe 0750 root reframe"