#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026-present Team LibreELEC (https://libreelec.tv)

# Require at least a package name.
[ $# -lt 1 ] && {
  echo "Usage: $0 PKG_NAME"
  exit 1
}

. config/options "${1}"

WORK_DIR="${PKG_DIR}/icon"

IMG_DIR="$DISTRO_DIR/$DISTRO/addons"
ADDON_INSTALL_DIR="${TARGET_IMG}/${ADDONS}/${ADDON_VERSION}/${DEVICE:-${PROJECT}}/${TARGET_ARCH}/${PKG_ADDON_ID}"

# Determine icon name, if "none" dont add text
if [ -n "$PKG_ADDON_ICON_NAME" ] && [ "$PKG_ADDON_ICON_NAME" != "none" ]; then
  ICON_NAME="$PKG_ADDON_ICON_NAME"
elif [ "$PKG_ADDON_ICON_NAME" = "none" ]; then
  ICON_NAME=""
else
  ICON_NAME="$PKG_ADDON_NAME"
fi

# Determine overlay type
if [[ "$PKG_DIR" == *"packages/addons/flatpak"* ]]; then
  ICON_OVERLAY="yes"
  ICON_OVERLAY_IMG="overlay-flatpack.png"
fi

# Create temp files
TMP_ICON=$(mktemp --suffix=.png)
TMP_OVERLAY=$(mktemp --suffix=.png)
TMP_SHADOW=$(mktemp --suffix=.png)

# icon use svg or png
if [ -f "${WORK_DIR}/icon-source.svg" ]; then
  SRC_ICON=$(mktemp --suffix=.png)
  # rsvg-convert resize has bad quality, so we convert to png first and then use convert to resize
  rsvg-convert -w 1500 "${WORK_DIR}/icon-source.svg" -o "$SRC_ICON"
elif [ -f "${WORK_DIR}/icon-source.png" ]; then
  SRC_ICON="${WORK_DIR}/icon-source.png"
else
  die "No icon-source.svg or icon-source.png found in ${WORK_DIR}"
fi

# icon resize
convert -background none -density 300 "$SRC_ICON" -strip -resize "${PKG_ADDON_ICON_SIZE:-222}x${PKG_ADDON_ICON_SIZE:-222}" "$TMP_ICON"

# icon create drop shadow
convert "$TMP_ICON" \
  \( +clone -background black -shadow 60x4+2+2 \) \
  +swap -background none -layers merge +repage \
  "$TMP_ICON"

# overlay resize and drop shadow
if [ "$ICON_OVERLAY" = "yes" ]; then
  # Resize
  convert -background none "${IMG_DIR}/$ICON_OVERLAY_IMG" -resize 80 "$TMP_OVERLAY"

  # create drop shadow
  convert "$TMP_OVERLAY" \
    \( +clone -background black -shadow 60x4+2+2 \) \
    +swap -background none -layers merge +repage \
    "$TMP_SHADOW"
fi

mkdir -p "${ADDON_INSTALL_DIR}/resources"

# Compose final image
convert_args=(
  "${IMG_DIR}/addon-bg.png"
  "$TMP_ICON" -gravity center -geometry "+0${PKG_ADDON_ICON_OFFSET:--36}" -composite
)

if [ "$ICON_OVERLAY" = "yes" ]; then
  convert_args+=(
    "$TMP_SHADOW" -gravity southeast -geometry +55${PKG_ADDON_ICON_OVERLAY_OFFSET:-+105} -composite
  )
fi

convert_args+=(
  -gravity south -font "${IMG_DIR}/calibrib.ttf" -pointsize 60 -fill "#E7E7E7"
  -annotate +0+50 "${ICON_NAME^^}"
  "${WORK_DIR}/icon.png"
)

convert "${convert_args[@]}"

echo "Icon created for ${PKG_NAME} at ${WORK_DIR}/icon.png"

# Cleanup
rm "$TMP_ICON" "$TMP_OVERLAY" "$TMP_SHADOW"
